/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Programador;
import model.Sexo;
import data.MemoryDataBank;
/**
 *
 * @author crfranco
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    
    MemoryDataBank md = new MemoryDataBank();
    
    public Principal() {
        initComponents();
        buttonGroup1.add(rbFeminino);
        buttonGroup1.add(rbMasculino);
        this.setSize(1024,738);
        this.setLocationRelativeTo(null);
        
        this.setStatusFormulario(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelNorte = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        painelSul = new javax.swing.JPanel();
        btAtualizar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        painelCentro = new javax.swing.JPanel();
        lbId = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbSexo = new javax.swing.JLabel();
        lbLinguagens = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        lbObservacao = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        txNome = new javax.swing.JTextField();
        rbFeminino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        ckJava = new javax.swing.JCheckBox();
        ckPython = new javax.swing.JCheckBox();
        ckKotlin = new javax.swing.JCheckBox();
        cmCidade = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObservacao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicação Swing 1.0");
        setResizable(false);

        painelNorte.setBackground(new java.awt.Color(255, 255, 102));
        painelNorte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        painelNorte.add(btNovo);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        painelNorte.add(btSalvar);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        painelNorte.add(btCancelar);

        getContentPane().add(painelNorte, java.awt.BorderLayout.PAGE_START);

        painelSul.setBackground(new java.awt.Color(255, 204, 204));

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });
        painelSul.add(btAtualizar);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        painelSul.add(btBuscar);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        painelSul.add(btExcluir);

        getContentPane().add(painelSul, java.awt.BorderLayout.PAGE_END);

        painelCentro.setBackground(new java.awt.Color(255, 255, 255));
        painelCentro.setLayout(null);

        lbId.setText("Código");
        painelCentro.add(lbId);
        lbId.setBounds(80, 60, 33, 14);

        lbNome.setText("Nome");
        painelCentro.add(lbNome);
        lbNome.setBounds(80, 100, 27, 14);

        lbSexo.setText("Sexo");
        painelCentro.add(lbSexo);
        lbSexo.setBounds(80, 150, 24, 14);

        lbLinguagens.setText("Linguagens de Programação");
        painelCentro.add(lbLinguagens);
        lbLinguagens.setBounds(80, 200, 190, 14);

        lbCidade.setText("Cidade");
        painelCentro.add(lbCidade);
        lbCidade.setBounds(80, 270, 45, 14);

        lbObservacao.setText("Observação");
        painelCentro.add(lbObservacao);
        lbObservacao.setBounds(80, 320, 90, 14);

        txId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelCentro.add(txId);
        txId.setBounds(300, 50, 80, 26);

        txNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelCentro.add(txNome);
        txNome.setBounds(300, 100, 260, 16);

        rbFeminino.setText("Feminino");
        painelCentro.add(rbFeminino);
        rbFeminino.setBounds(300, 150, 67, 23);

        rbMasculino.setText("Masculino");
        painelCentro.add(rbMasculino);
        rbMasculino.setBounds(410, 150, 71, 20);

        ckJava.setText("Java");
        painelCentro.add(ckJava);
        ckJava.setBounds(300, 200, 49, 23);

        ckPython.setText("Python");
        painelCentro.add(ckPython);
        ckPython.setBounds(360, 200, 59, 23);

        ckKotlin.setText("Kotlin");
        painelCentro.add(ckKotlin);
        ckKotlin.setBounds(440, 200, 51, 23);

        cmCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blumenau", "Ilhota", "Guaramirim", "Jaragua do Sul", "Xereder" }));
        painelCentro.add(cmCidade);
        cmCidade.setBounds(310, 270, 150, 20);

        taObservacao.setColumns(20);
        taObservacao.setRows(5);
        jScrollPane1.setViewportView(taObservacao);

        painelCentro.add(jScrollPane1);
        jScrollPane1.setBounds(250, 300, 166, 96);

        getContentPane().add(painelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.limpaFormulario();
        this.setStatusFormulario(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        this.setStatusFormulario(true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        error = false;
        this.criaProgramador();
 
        md.save(programador);
        this.validaFormulario();
        
        if(!error)
            btCancelar.doClick();
        
        System.out.println(md.list());
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        
        System.out.println(md.getOne(Integer.parseInt(txId.getText())));
        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        md.delete(Integer.parseInt(txId.getText()));
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        md.update(Integer.parseInt(txId.getText()), programador);
        
        System.out.println(md.list());
    }//GEN-LAST:event_btAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        MemoryDataBank md = new MemoryDataBank();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
        
    }
    
    
    private void validaFormulario(){
        String message = "Os seguintes campos náo estão preenchidos";
        
        
        if(txNome.getText().length()==0){ 
            message+="\n Nome";
            error = true;
        }
        
        if(!rbFeminino.isSelected() && !rbMasculino.isSelected()){ 
            message +="\n Sexo";
            error = true;
        }
        
        if(programador.getLinguagensProgramacao().length == 0){
            message +="\n Linguagens de programaçao";
            error = true;
        }
        if (error)    
            JOptionPane.showMessageDialog(null, message);
    }
    
    private void limpaFormulario(){
       txId.setText("");
       txNome.setText("");
       buttonGroup1.clearSelection();
       
       
       ckJava.setEnabled(false);
       ckPython.setEnabled(false);
       ckKotlin.setEnabled(false);
       cmCidade.setSelectedIndex(0);
       taObservacao.setText("");
    }
    
    private void setStatusFormulario(boolean status){
       
       txNome.setEnabled(status);
       rbMasculino.setEnabled(status);
       rbFeminino.setEnabled(status);
       ckJava.setEnabled(status);
       ckPython.setEnabled(status);
       ckKotlin.setEnabled(status);
       cmCidade.setEnabled(status);
       taObservacao.setEnabled(status);
    }
    
    private void criaProgramador(){
        
        
        
        String nome = txNome.getText();
         
        Sexo sexo = rbMasculino.isSelected()? Sexo.MASCULINO : Sexo.FEMININO;
        
        String cidade = cmCidade.getSelectedItem().toString();
        
        List<String> listaLinguagens = new ArrayList<>();
        
        if(ckJava.isSelected()) listaLinguagens.add("Java");
        if(ckKotlin.isSelected()) listaLinguagens.add("kotlin");
        if(ckPython.isSelected()) listaLinguagens.add("Python");
        
        String[] linguagens = new String[listaLinguagens.size()];
        
        linguagens = listaLinguagens.toArray(linguagens);
        
        String observacao = taObservacao.getText();
        
        programador = new Programador(nome, sexo, linguagens, cidade, observacao);
        programador.setCodigo(Integer.parseInt(txId.getText()));
        
        
       
        
    }
    private Programador programador;
    private boolean error;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckJava;
    private javax.swing.JCheckBox ckKotlin;
    private javax.swing.JCheckBox ckPython;
    private javax.swing.JComboBox<String> cmCidade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbLinguagens;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbObservacao;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JPanel painelCentro;
    private javax.swing.JPanel painelNorte;
    private javax.swing.JPanel painelSul;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextArea taObservacao;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txNome;
    // End of variables declaration//GEN-END:variables
}
